---
- name: Update cache and install required packages
  hosts: all
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts["os_family"] == 'Debian'
    - name: Install required packages
      ansible.builtin.package:
        name:
          - curl
          - mpd
          - mpc
          - default-jre-headless
          - unzip
        state: present
