---
- name: Reload systemd daemon
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true
  when: ansible_service_mgr == "systemd"

- name: Restart Asset UPNP service
  ansible.builtin.systemd_service:
    name: asset-upnp
    state: restarted
  become: true
  when: ansible_service_mgr == "systemd"
