---
gerbera_additional_groups: []

gerbera_server:
  name: "Clivia"
  udn: "{{ inventory_hostname | to_uuid }}"
  home: "/var/lib/gerbera"
  manufacturer: "Gerbera"
  manufacturer_url: "https://gerbera.io"
  webroot: "/usr/share/gerbera/web"
  alive: 1800
  pc_directory_hide: false
  ui:
    enabled: true
    show_tooltips: true
  accounts:
    enabled: true
    session_timeout: 30
    user: gerbera
    password: gerbera
  storage:
    use_transactions: false
    sqlite3:
      enabled: true
      database_file: "gerbera.db"
    mysql:
      enabled: false

gerbera_music_group_name: music
gerbera_music_directories:
  - /audio
gerbera_music_group_users:
  - gerbera
