---
- name: Converge (RPi4 Test)
  hosts: all
  vars:
    # Container-specific overrides for testing
    mediaplayer_test_mode: true
  roles:
    - role: mediaplayer
      vars:
        mediaplayer_install_location: /opt/mediaplayer
        mediaplayer_user_name: mediaplayer
        mediaplayer_user_group: mediaplayer
        mediaplayer_service_name: mediaplayer
        radios:
          - name: 'France Culture'
            stream: 'http://direct.franceculture.fr/live/franceculture-midfi.mp3'
            img: 'https://gitlab.com/f.ansible/ansible-mediaplayer/-/raw/master/extra/france-culture.png'
          - name: 'RTE lyrics'
            stream: 'http://radio.linnrecords.com/cast/tunein.php/linnclassical/playlist.pls'
            img: 'http://cdn-radiotime-logos.tunein.com/s122116q.png'