---
# Molecule converge playbook for gerbera role

- name: Converge
  hosts: test_instances

  tasks:
    - name: Include the gerbera role
      ansible.builtin.include_role:
        name: "{{ playbook_dir | dirname | dirname }}"
