---
- name: Debug role variables
  hosts: localhost
  gather_facts: true
  roles:
    - role: gerbera
      when: false
  tasks:
    - name: Print gerbera server name
      ansible.builtin.debug:
        var: gerbera_server.name
