pcm.pulse {
   type pulse
   card "sndrpihifiberry"
}
ctl.pulse {
   type pulse
   card "sndrpihifiberry"
}
pcm.!default {
   type hw
   card "sndrpihifiberry"
}
ctl.!default {
   type hw
   card "sndrpihifiberry"
}
