---
galaxy_info:
  role_name: mediaplayer
  namespace: fesaille
  author: Emmanuel Roux
  description: Install and configure MediaPlayer on Debian
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: Ubuntu
      versions:
        - noble

  galaxy_tags: []

dependencies: []
